### ISSUE TITLE
Make an option to auto wrap or collapse

### ISSUE THREAD

**Issue by john-peterson** [yoheimuta/github-pre-utility#3]
so i dont have to press a key

**Comment by yoheimuta** [comment]
Thank you. I understand it. 

I'm going to make an option in v0.0.2.

**Comment by yoheimuta** [comment]
@john-peterson I published v0.0.2. please check it.

**Comment by john-peterson** [comment]
thx worx i tested here https://github.com/yoheimuta/github-pre-utility/issues/1

**Comment by yoheimuta** [comment]
:+1:
